### ISSUE TITLE
Some questions about PyQt5

### ISSUE THREAD

**Issue by Jeff-liaojinfu** [sciapp/nojava-ipmi-kvm#1]
Hi：

When I use nojava-ipmi-kvm 0.1.4, Some questions about PyQt5

When I execute nojava-ipmi-kvm , I throw the following exception:
File "/usr/python37/lib/python3.7/site-packages/nojava_ipmi_kvm/browser.py", line 22, in <module>
    from PyQt5 import QtCore, QtWidgets, QtWebEngineWidgets
ImportError: cannot import name 'QtWebEngineWidgets' from 'PyQt5' (/usr/python37/lib/python3.7/site-packages/PyQt5/__init__.py)

 The version I am using is PyQt5==5.12.1, there is no such module QtWebEngineWidgets. Which version do you use?

**Comment by IngoHeimbach** [comment]
Hey,
thanks for trying out `nojava-ipmi-kvm`. Not all versions of PyQt5 (for example from conda) include the web engine part of the library. How did you install PyQt5 and this project?

**Comment by Jeff-liaojinfu** [comment]
Thanks for answer
I think this is my current problem.
I use pip3 to install the PyQt5 package,but no QtWebEngine 
I am working on a bare metal product on a cloud platform. Your project is estimated to be very helpful for me to develop a web console. Can you provide me with your installation package?

**Comment by IngoHeimbach** [comment]
I was a bit confused that the PyPI package did not work (because I am sure I was working in the past). The reason is a [packaging change in the PyQt5 project](https://www.riverbankcomputing.com/news/pyqt-512). Now, QtWebEngine is  a separate package that must be added as a dependency to this project. The dependencies are updated with the lastest release [v0.1.5](https://pypi.org/project/nojava-ipmi-kvm/0.1.5/). Now, you should be able to install `nojava-ipmi-kvm` with `pip3`. There is no need to compile Qt or PyQt yourself.
